package app.varlorg.unote;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.filters.LargeTest;

import org.junit.Test;
import org.junit.runner.RunWith;

import static androidx.test.espresso.action.ViewActions.closeSoftKeyboard;
import static androidx.test.espresso.Espresso.onView;
import static androidx.test.espresso.action.ViewActions.clearText;
import static androidx.test.espresso.action.ViewActions.click;
import static androidx.test.espresso.action.ViewActions.replaceText;
import static androidx.test.espresso.assertion.ViewAssertions.matches;
import static androidx.test.espresso.matcher.ViewMatchers.isDisplayed;
import static androidx.test.espresso.matcher.ViewMatchers.withId;
import static androidx.test.espresso.matcher.ViewMatchers.withText;

@RunWith(AndroidJUnit4.class)
@LargeTest
public class Struct2TestGeneratedTest {

    @Test
    public void generatedFromHierarchy_noteEditorTest() {
        onView(withText("uNote")).check(matches(isDisplayed()));
        onView(withId(R.id.TitreNoteEdition)).check(matches(isDisplayed()));
        onView(withId(R.id.NoteEdition)).check(matches(isDisplayed()));
        onView(withId(R.id.ButtonSave)).check(matches(isDisplayed()));
        onView(withId(R.id.ButtonQuit)).check(matches(isDisplayed()));

        onView(withId(R.id.TitreNoteEdition))
                .perform(clearText(), replaceText("Test Title"), closeSoftKeyboard());

        onView(withId(R.id.NoteEdition))
                .perform(clearText(), replaceText("Test note body generated by Struct2Test."), closeSoftKeyboard());

        onView(withId(R.id.ButtonSave)).perform(click());
    }
}
